name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby
    strategy:
      matrix:
        ruby:
          - '3.1.0'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    
    - name: Install dependencies
      run: make install

    - name: Run Rubocop
      run: make lint

    - name: Run tests
      run: make tests
    
    - name: code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: 3ea29d5ee73467ec159b9300fbdd666da8062090573583c76cf46cba49d88d22
      with:
        coverageCommand: make tests